from __future__ import absolute_import
from __future__ import division
from __future__ import print_function

from pyoneer.metrics.metrics import MeanAbsolutePercentageError
from pyoneer.metrics.metrics import SymmetricMeanAbsolutePercentageError
from pyoneer.metrics.metrics import mean_absolute_percentage_error
from pyoneer.metrics.metrics import symmetric_mean_absolute_percentage_error

from pyoneer.metrics.metrics import MeanAbsolutePercentageError as MAPE
from pyoneer.metrics.metrics import SymmetricMeanAbsolutePercentageError as SMAPE
from pyoneer.metrics.metrics import mean_absolute_percentage_error as mape
from pyoneer.metrics.metrics import symmetric_mean_absolute_percentage_error as smape
